// <auto-generated />
using System;
using Beacon.SampleProject.Warp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beacon.SampleProject.Warp.Migrations
{
    [DbContext(typeof(WarpDbContext))]
    [Migration("20260710141352_WarpInitial")]
    partial class WarpInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warp.Core.Data.Entities.BackgroundServiceDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("DeclaredScope")
                        .HasColumnType("integer")
                        .HasColumnName("declared_scope");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Name")
                        .HasName("pk_background_service_definition");

                    b.ToTable("background_service_definition", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.BackgroundServiceInstance", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_name");

                    b.Property<int>("DeclaredScope")
                        .HasColumnType("integer")
                        .HasColumnName("declared_scope");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_error_at");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<int>("RestartCount")
                        .HasColumnType("integer")
                        .HasColumnName("restart_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("ServerId", "ServiceName")
                        .HasName("pk_background_service_instance");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_background_service_instance_server_id");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("ix_background_service_instance_service_name");

                    b.ToTable("background_service_instance", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.BackgroundServiceLease", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_name");

                    b.Property<Guid>("HolderServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("holder_server_id");

                    b.Property<DateTime>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.HasKey("ServiceName")
                        .HasName("pk_background_service_lease");

                    b.HasIndex("HolderServerId")
                        .HasDatabaseName("ix_background_service_lease_holder_server_id");

                    b.ToTable("background_service_lease", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.BackgroundServiceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("exception_message");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("exception_type");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("message");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_name");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_background_service_log");

                    b.HasIndex("ServiceName", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_background_service_log_service_name_id");

                    b.HasIndex("ServerId", "ServiceName", "Id")
                        .HasDatabaseName("ix_background_service_log_server_id_service_name_id");

                    b.ToTable("background_service_log", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.CircuitBreakerState", b =>
                {
                    b.Property<string>("GroupKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_key");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<DateTime>("LastFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_at");

                    b.Property<DateTime?>("OpenUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_until");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("GroupKey")
                        .HasName("pk_circuit_breaker_state");

                    b.HasIndex("OpenUntil")
                        .HasDatabaseName("ix_circuit_breaker_state_open_until");

                    b.ToTable("circuit_breaker_state", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.ConcurrencyLimit", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Limit")
                        .HasColumnType("integer")
                        .HasColumnName("limit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_concurrency_limit");

                    b.ToTable("concurrency_limit", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_counter");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_counter_key");

                    b.ToTable("counter", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.JobLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<short?>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_job_log");

                    b.HasIndex("JobId", "EventType", "Timestamp")
                        .HasDatabaseName("ix_job_log_job_id_event_type_timestamp");

                    b.ToTable("job_log", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.RateLimitBucket", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_count");

                    b.Property<string>("TimestampsJson")
                        .HasColumnType("text")
                        .HasColumnName("timestamps_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc");

                    b.HasKey("Name")
                        .HasName("pk_rate_limit_bucket");

                    b.ToTable("rate_limit_bucket", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.RateLimitOverride", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("window_seconds");

                    b.HasKey("Name")
                        .HasName("pk_rate_limit_override");

                    b.ToTable("rate_limit_override", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.RecurringJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cron")
                        .HasColumnType("text")
                        .HasColumnName("cron");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<DateTime?>("LastExecution")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_execution");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextExecution")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_execution");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_recurring_job");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_recurring_job_name");

                    b.ToTable("recurring_job", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.RecurringJobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("RecurringJobId")
                        .HasColumnType("integer")
                        .HasColumnName("recurring_job_id");

                    b.Property<bool>("Skipped")
                        .HasColumnType("boolean")
                        .HasColumnName("skipped");

                    b.HasKey("Id")
                        .HasName("pk_recurring_job_log");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_recurring_job_log_job_id");

                    b.HasIndex("RecurringJobId")
                        .HasDatabaseName("ix_recurring_job_log_recurring_job_id");

                    b.ToTable("recurring_job_log", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.SagaJobLink", b =>
                {
                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("SagaId", "JobId")
                        .HasName("pk_saga_job_link");

                    b.HasIndex("SagaId", "CreatedAt")
                        .HasDatabaseName("ix_saga_job_link_saga_id_created_at");

                    b.ToTable("saga_job_link", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.SagaState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state_json");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_saga_state");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_saga_state_created_at");

                    b.HasIndex("Type", "CorrelationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_saga_state_type_correlation_key");

                    b.ToTable("saga_state", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<DateTime>("LastHeartbeatTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_time");

                    b.Property<long?>("MemoryWorkingSetBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_working_set_bytes");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_name");

                    b.Property<int>("ServiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("service_count");

                    b.Property<DateTime>("StartedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_time");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.ToTable("server", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.ServerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int?>("ServerTaskId")
                        .HasColumnType("integer")
                        .HasColumnName("server_task_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_server_log");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_log_server_id");

                    b.HasIndex("ServerTaskId")
                        .HasDatabaseName("ix_server_log_server_task_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_server_log_timestamp");

                    b.ToTable("server_log", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.ServerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("IntervalSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("interval_seconds");

                    b.Property<double?>("LastDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("last_duration_ms");

                    b.Property<string>("LastMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_message");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run");

                    b.Property<string>("LastStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_status");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_name");

                    b.HasKey("Id")
                        .HasName("pk_server_task");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_task_server_id");

                    b.ToTable("server_task", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.Statistic", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_statistic");

                    b.ToTable("statistic", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastHeartbeatTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_time");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("StartedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_time");

                    b.Property<Guid?>("WorkerGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_group_id");

                    b.HasKey("Id")
                        .HasName("pk_worker");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_worker_server_id");

                    b.HasIndex("WorkerGroupId")
                        .HasDatabaseName("ix_worker_worker_group_id");

                    b.ToTable("worker", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.WorkerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<double>("PollingIntervalMs")
                        .HasColumnType("double precision")
                        .HasColumnName("polling_interval_ms");

                    b.Property<string>("Queues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queues");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("integer")
                        .HasColumnName("worker_count");

                    b.HasKey("Id")
                        .HasName("pk_worker_group");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_worker_group_server_id");

                    b.ToTable("worker_group", "warp");
                });

            modelBuilder.Entity("Warp.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CancellationMode")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_mode");

                    b.Property<int?>("ContinuationOptions")
                        .HasColumnType("integer")
                        .HasColumnName("continuation_options");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer")
                        .HasColumnName("current_state");

                    b.Property<Guid?>("CurrentWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_worker_id");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_at");

                    b.Property<string>("HandlerType")
                        .HasColumnType("text")
                        .HasColumnName("handler_type");

                    b.Property<int>("JobCount")
                        .HasColumnType("integer")
                        .HasColumnName("job_count");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastKeepAlive")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_keep_alive");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_job_id");

                    b.Property<string>("ParentSpanId")
                        .HasColumnType("text")
                        .HasColumnName("parent_span_id");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<int>("RetriedTimes")
                        .HasColumnType("integer")
                        .HasColumnName("retried_times");

                    b.Property<DateTime>("ScheduleTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("schedule_time");

                    b.Property<Guid?>("SpawnedByJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("spawned_by_job_id");

                    b.Property<Guid?>("TraceId")
                        .HasColumnType("uuid")
                        .HasColumnName("trace_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_job");

                    b.HasIndex("ExpireAt")
                        .HasDatabaseName("ix_job_expire_at");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_job_trace_id");

                    b.HasIndex("ParentJobId", "CurrentState")
                        .HasDatabaseName("ix_job_parent_job_id_current_state");

                    b.HasIndex("Kind", "CurrentState", "CreateTime")
                        .HasDatabaseName("ix_job_kind_current_state_create_time");

                    b.HasIndex("Kind", "CurrentState", "Queue", "ScheduleTime")
                        .HasDatabaseName("ix_job_kind_current_state_queue_schedule_time");

                    b.ToTable("job", "warp");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.BackgroundServiceInstance", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_background_service_instance_server_server_id");

                    b.HasOne("Warp.Core.Data.Entities.BackgroundServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_background_service_instance_background_service_definition_s");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.BackgroundServiceLease", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.Server", "HolderServer")
                        .WithMany()
                        .HasForeignKey("HolderServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_background_service_lease_server_holder_server_id");

                    b.HasOne("Warp.Core.Data.Entities.BackgroundServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_background_service_lease_background_service_definition_serv");

                    b.Navigation("HolderServer");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.BackgroundServiceLog", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_background_service_log_server_server_id");

                    b.HasOne("Warp.Core.Data.Entities.BackgroundServiceInstance", null)
                        .WithMany()
                        .HasForeignKey("ServerId", "ServiceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_background_service_log_background_service_instance_server_i");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.RecurringJobLog", b =>
                {
                    b.HasOne("Warp.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recurring_job_log_job_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.SagaJobLink", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.SagaState", null)
                        .WithMany()
                        .HasForeignKey("SagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saga_job_link_saga_state_saga_id");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.ServerLog", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.Server", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_log_server_server_id");

                    b.HasOne("Warp.Core.Data.Entities.ServerTask", "ServerTask")
                        .WithMany()
                        .HasForeignKey("ServerTaskId")
                        .HasConstraintName("fk_server_log_server_task_server_task_id");

                    b.Navigation("ServerTask");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.ServerTask", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.Server", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_task_server_server_id");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.Worker", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_server_server_id");

                    b.HasOne("Warp.Core.Data.Entities.WorkerGroup", "WorkerGroup")
                        .WithMany()
                        .HasForeignKey("WorkerGroupId")
                        .HasConstraintName("fk_worker_worker_group_worker_group_id");

                    b.Navigation("Server");

                    b.Navigation("WorkerGroup");
                });

            modelBuilder.Entity("Warp.Core.Data.Entities.WorkerGroup", b =>
                {
                    b.HasOne("Warp.Core.Data.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_group_server_server_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Warp.Core.Entities.Job", b =>
                {
                    b.HasOne("Warp.Core.Entities.Job", "ParentJob")
                        .WithMany("ChildJobs")
                        .HasForeignKey("ParentJobId")
                        .HasConstraintName("fk_job_job_parent_job_id");

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("Warp.Core.Entities.Job", b =>
                {
                    b.Navigation("ChildJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
