// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Semantico.Core.PostgreSql.Data;

#nullable disable

namespace Semantico.Core.PostgreSql.Data.Migrations
{
    [DbContext(typeof(PostgreSqlSemanticoContext))]
    [Migration("20260112161235_AiWorkflow")]
    partial class AiWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("semantico")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.Property<int>("RecipientsId")
                        .HasColumnType("integer")
                        .HasColumnName("recipients_id");

                    b.Property<int>("SubscriptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("subscriptions_id");

                    b.HasKey("RecipientsId", "SubscriptionsId")
                        .HasName("pk_recipient_subscription");

                    b.HasIndex("SubscriptionsId")
                        .HasDatabaseName("ix_recipient_subscription_subscriptions_id");

                    b.ToTable("recipient_subscription", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiAlertConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<int>("ConversationTurns")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_turns");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("FinalSql")
                        .HasColumnType("text")
                        .HasColumnName("final_sql");

                    b.Property<string>("GeneratedByModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_by_model");

                    b.Property<string>("GeneratedSql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_sql");

                    b.Property<string>("GenerationReasoning")
                        .HasColumnType("text")
                        .HasColumnName("generation_reasoning");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NaturalLanguageDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("natural_language_description");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<string>("UserFeedback")
                        .HasColumnType("text")
                        .HasColumnName("user_feedback");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text")
                        .HasColumnName("validation_errors");

                    b.HasKey("Id")
                        .HasName("pk_ai_alert_configurations");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_ai_alert_configurations_data_source_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ai_alert_configurations_status");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_ai_alert_configurations_subscription_id");

                    b.ToTable("ai_alert_configurations", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiConversationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AiAlertConfigurationId")
                        .HasColumnType("integer")
                        .HasColumnName("ai_alert_configuration_id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_content");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.HasKey("Id")
                        .HasName("pk_ai_conversation_histories");

                    b.HasIndex("AiAlertConfigurationId")
                        .HasDatabaseName("ix_ai_conversation_histories_ai_alert_configuration_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_ai_conversation_histories_timestamp");

                    b.HasIndex("TurnNumber")
                        .HasDatabaseName("ix_ai_conversation_histories_turn_number");

                    b.ToTable("ai_conversation_histories", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiPromptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("operation_type");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_template");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature");

                    b.Property<string>("VariableDefinitions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variable_definitions");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ai_prompt_templates");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_ai_prompt_templates_is_active");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("ix_ai_prompt_templates_operation_type");

                    b.ToTable("ai_prompt_templates", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiUsageMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("alert_config_id");

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<int?>("DocumentationId")
                        .HasColumnType("integer")
                        .HasColumnName("documentation_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("operation_type");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<bool>("PromptCacheHit")
                        .HasColumnType("boolean")
                        .HasColumnName("prompt_cache_hit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<int?>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_usage_metrics");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_ai_usage_metrics_data_source_id");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("ix_ai_usage_metrics_operation_type");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_ai_usage_metrics_provider");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_ai_usage_metrics_query_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_ai_usage_metrics_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_usage_metrics_user_id");

                    b.ToTable("ai_usage_metrics", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AnomalyBaseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("numeric")
                        .HasColumnName("metric_value");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_anomaly_baselines");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("ix_anomaly_baselines_execution_time");

                    b.HasIndex("SubscriptionId", "ExecutionTime")
                        .HasDatabaseName("ix_anomaly_baselines_subscription_id_execution_time");

                    b.ToTable("anomaly_baselines", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AnomalyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertOnDecrease")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_on_decrease");

                    b.Property<bool>("AlertOnIncrease")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_on_increase");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DetectionMethod")
                        .HasColumnType("integer")
                        .HasColumnName("detection_method");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("integer")
                        .HasColumnName("lookback_days");

                    b.Property<int>("MinimumDataPoints")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_data_points");

                    b.Property<int>("Sensitivity")
                        .HasColumnType("integer")
                        .HasColumnName("sensitivity");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_anomaly_configs");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_anomaly_configs_enabled");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_anomaly_configs_subscription_id");

                    b.ToTable("anomaly_configs", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AnomalyEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("acknowledged");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("acknowledged_by");

                    b.Property<DateTime?>("AcknowledgedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_time");

                    b.Property<decimal?>("BaselineMean")
                        .HasColumnType("numeric")
                        .HasColumnName("baseline_mean");

                    b.Property<decimal?>("BaselineStdDev")
                        .HasColumnType("numeric")
                        .HasColumnName("baseline_std_dev");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("numeric")
                        .HasColumnName("current_value");

                    b.Property<DateTime>("DetectedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_time");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<int?>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<decimal?>("ZScore")
                        .HasColumnType("numeric")
                        .HasColumnName("z_score");

                    b.HasKey("Id")
                        .HasName("pk_anomaly_events");

                    b.HasIndex("DetectedTime")
                        .HasDatabaseName("ix_anomaly_events_detected_time");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_anomaly_events_notification_id");

                    b.HasIndex("Acknowledged", "DetectedTime")
                        .HasDatabaseName("ix_anomaly_events_acknowledged_detected_time");

                    b.HasIndex("SubscriptionId", "DetectedTime")
                        .HasDatabaseName("ix_anomaly_events_subscription_id_detected_time");

                    b.ToTable("anomaly_events", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("CreatedTime")
                        .HasDatabaseName("ix_comments_created_time");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_comments_entity_type_entity_id");

                    b.ToTable("comments", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DestinationRowsWritten")
                        .HasColumnType("integer")
                        .HasColumnName("destination_rows_written");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("EstimatedTotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_total_rows");

                    b.Property<string>("ExecutedQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("executed_query");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("integer")
                        .HasColumnName("migration_job_id");

                    b.Property<int?>("ParentExecutionId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_execution_id");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<string>("QueryParameters")
                        .HasColumnType("text")
                        .HasColumnName("query_parameters");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("retry_attempt");

                    b.Property<int>("RowsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("rows_failed");

                    b.Property<int>("RowsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("rows_skipped");

                    b.Property<int>("SourceRowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("source_rows_read");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TransformationApplied")
                        .HasColumnType("text")
                        .HasColumnName("transformation_applied");

                    b.HasKey("Id")
                        .HasName("pk_migration_executions");

                    b.HasIndex("MigrationJobId")
                        .HasDatabaseName("ix_migration_executions_migration_job_id");

                    b.HasIndex("ParentExecutionId")
                        .HasDatabaseName("ix_migration_executions_parent_execution_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_migration_executions_started_at");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_migration_executions_status_started_at");

                    b.ToTable("migration_executions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_on");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DestinationDataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_data_source_id");

                    b.Property<string>("DestinationTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_table");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.Property<string>("Schedule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schedule");

                    b.Property<int>("TimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_minutes");

                    b.Property<string>("TransformationScript")
                        .HasColumnType("text")
                        .HasColumnName("transformation_script");

                    b.Property<bool>("ValidateBeforeExecution")
                        .HasColumnType("boolean")
                        .HasColumnName("validate_before_execution");

                    b.HasKey("Id")
                        .HasName("pk_migration_jobs");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_migration_jobs_data_source_id");

                    b.HasIndex("DestinationDataSourceId")
                        .HasDatabaseName("ix_migration_jobs_destination_data_source_id");

                    b.HasIndex("IsEnabled", "ArchivedTime")
                        .HasDatabaseName("ix_migration_jobs_is_enabled_archived_time");

                    b.ToTable("migration_jobs", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowSampleDataForAi")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_sample_data_for_ai");

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DatabaseEngineType")
                        .HasColumnType("integer")
                        .HasColumnName("database_engine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.ToTable("data_sources", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataSourceDocumentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedByModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_by_model");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("generated_by_user_id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<int?>("LastModifiedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TablesAnalyzed")
                        .HasColumnType("integer")
                        .HasColumnName("tables_analyzed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_data_source_documentations");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_data_source_documentations_data_source_id");

                    b.HasIndex("GeneratedAt")
                        .HasDatabaseName("ix_data_source_documentations_generated_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_data_source_documentations_status");

                    b.ToTable("data_source_documentations", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DocumentationAgentRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckpointStateJson")
                        .HasColumnType("text")
                        .HasColumnName("checkpoint_state_json");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedTablesJson")
                        .HasColumnType("text")
                        .HasColumnName("completed_tables_json");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("CurrentBatchIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_batch_index");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("integer")
                        .HasColumnName("current_phase");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("DiscoveredTablesJson")
                        .HasColumnType("text")
                        .HasColumnName("discovered_tables_json");

                    b.Property<int?>("DocumentationId")
                        .HasColumnType("integer")
                        .HasColumnName("documentation_id");

                    b.Property<string>("DomainGroupsJson")
                        .HasColumnType("text")
                        .HasColumnName("domain_groups_json");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("FailedTablesJson")
                        .HasColumnType("text")
                        .HasColumnName("failed_tables_json");

                    b.Property<DateTime?>("LastCheckpointAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checkpoint_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("progress_message");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("StartedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("started_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TablesCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("tables_completed");

                    b.Property<int>("TablesFailed")
                        .HasColumnType("integer")
                        .HasColumnName("tables_failed");

                    b.Property<int>("TotalTablesDiscovered")
                        .HasColumnType("integer")
                        .HasColumnName("total_tables_discovered");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_documentation_agent_runs");

                    b.HasIndex("CurrentPhase")
                        .HasDatabaseName("ix_documentation_agent_runs_current_phase");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_documentation_agent_runs_data_source_id");

                    b.HasIndex("DocumentationId")
                        .HasDatabaseName("ix_documentation_agent_runs_documentation_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_documentation_agent_runs_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documentation_agent_runs_status");

                    b.HasIndex("DataSourceId", "Status")
                        .HasDatabaseName("ix_documentation_agent_runs_data_source_id_status");

                    b.ToTable("documentation_agent_runs", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DocumentationSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiGeneratedContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_generated_content");

                    b.Property<int>("ContentFormat")
                        .HasColumnType("integer")
                        .HasColumnName("content_format");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DocumentationId")
                        .HasColumnType("integer")
                        .HasColumnName("documentation_id");

                    b.Property<bool>("IsUserEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_user_edited");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("SectionType")
                        .HasColumnType("integer")
                        .HasColumnName("section_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TableName")
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UserEditedContent")
                        .HasColumnType("text")
                        .HasColumnName("user_edited_content");

                    b.HasKey("Id")
                        .HasName("pk_documentation_sections");

                    b.HasIndex("DocumentationId")
                        .HasDatabaseName("ix_documentation_sections_documentation_id");

                    b.HasIndex("SectionType")
                        .HasDatabaseName("ix_documentation_sections_section_type");

                    b.HasIndex("TableName")
                        .HasDatabaseName("ix_documentation_sections_table_name");

                    b.ToTable("documentation_sections", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DocumentationVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("text")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DocumentationId")
                        .HasColumnType("integer")
                        .HasColumnName("documentation_id");

                    b.Property<int>("SectionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("sections_count");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_documentation_versions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_documentation_versions_created_at");

                    b.HasIndex("DocumentationId")
                        .HasDatabaseName("ix_documentation_versions_documentation_id");

                    b.ToTable("documentation_versions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.ColumnMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("column_name");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("data_type");

                    b.Property<int>("DatabaseMetadataId")
                        .HasColumnType("integer")
                        .HasColumnName("database_metadata_id");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ForeignKeyColumn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("foreign_key_column");

                    b.Property<string>("ForeignKeyTable")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("foreign_key_table");

                    b.Property<bool>("IsForeignKey")
                        .HasColumnType("boolean")
                        .HasColumnName("is_foreign_key");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nullable");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary_key");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal_position");

                    b.HasKey("Id")
                        .HasName("pk_column_metadata");

                    b.HasIndex("DatabaseMetadataId")
                        .HasDatabaseName("ix_column_metadata_database_metadata_id");

                    b.HasIndex("DatabaseMetadataId", "ColumnName")
                        .HasDatabaseName("ix_column_metadata_database_metadata_id_column_name");

                    b.ToTable("column_metadata", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<DateTime>("LastRefreshed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schema_name");

                    b.Property<string>("TableDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("table_description");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_name");

                    b.HasKey("Id")
                        .HasName("pk_database_metadata");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_database_metadata_data_source_id");

                    b.HasIndex("LastRefreshed")
                        .HasDatabaseName("ix_database_metadata_last_refreshed");

                    b.HasIndex("DataSourceId", "SchemaName", "TableName")
                        .IsUnique()
                        .HasDatabaseName("ix_database_metadata_data_source_id_schema_name_table_name");

                    b.ToTable("database_metadata", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.IndexMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("Columns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("columns");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DatabaseMetadataId")
                        .HasColumnType("integer")
                        .HasColumnName("database_metadata_id");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("index_name");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary_key");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.HasKey("Id")
                        .HasName("pk_index_metadata");

                    b.HasIndex("DatabaseMetadataId")
                        .HasDatabaseName("ix_index_metadata_database_metadata_id");

                    b.ToTable("index_metadata", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("QueryExecutionHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_execution_history_id");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Results")
                        .HasColumnType("text")
                        .HasColumnName("results");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int?>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("QueryExecutionHistoryId")
                        .HasDatabaseName("ix_notifications_query_execution_history_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notifications_recipient_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_notifications_task_id");

                    b.ToTable("notifications", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FinalQuery")
                        .HasColumnType("text")
                        .HasColumnName("final_query");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.ToTable("queries", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompiledSql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compiled_sql");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<double>("ExecutionTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("execution_time_ms");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("notification_status");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<string>("Results")
                        .HasColumnType("text")
                        .HasColumnName("results");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_query_execution_history");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_query_execution_history_subscription_id");

                    b.ToTable("query_execution_history", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placeholder");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_query_parameters");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_query_parameters_query_id");

                    b.ToTable("query_parameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<string>("SqlValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_value");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_query_steps");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_query_steps_data_source_id");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_query_steps_query_id");

                    b.ToTable("query_steps", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Placeholder")
                        .HasColumnType("text")
                        .HasColumnName("placeholder");

                    b.Property<int>("QueryStepId")
                        .HasColumnType("integer")
                        .HasColumnName("query_step_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_query_step_parameters");

                    b.HasIndex("QueryStepId")
                        .HasDatabaseName("ix_query_step_parameters_query_step_id");

                    b.ToTable("query_step_parameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastNotificationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notification_at");

                    b.Property<int>("LatestResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("latest_result_count");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_notes");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_query_tasks");

                    b.HasIndex("CreatedTime")
                        .HasDatabaseName("ix_query_tasks_created_time");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_query_tasks_subscription_id");

                    b.HasIndex("Resolved", "CreatedTime")
                        .HasDatabaseName("ix_query_tasks_resolved_created_time");

                    b.ToTable("query_tasks", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.HasKey("Id")
                        .HasName("pk_recipients");

                    b.ToTable("recipients", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<bool>("CreateTasks")
                        .HasColumnType("boolean")
                        .HasColumnName("create_tasks");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IncludeAttachment")
                        .HasColumnType("boolean")
                        .HasColumnName("include_attachment");

                    b.Property<int?>("MaxRows")
                        .HasColumnType("integer")
                        .HasColumnName("max_rows");

                    b.Property<int>("NotificationTrigger")
                        .HasColumnType("integer")
                        .HasColumnName("notification_trigger");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<int?>("ResultAttachmentType")
                        .HasColumnType("integer")
                        .HasColumnName("result_attachment_type");

                    b.Property<bool>("ShowQuery")
                        .HasColumnType("boolean")
                        .HasColumnName("show_query");

                    b.Property<bool>("StoreResults")
                        .HasColumnType("boolean")
                        .HasColumnName("store_results");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_subscriptions_query_id");

                    b.ToTable("subscriptions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("QueryPlaceholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_placeholder");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_subscription_parameters");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_parameters_subscription_id");

                    b.ToTable("subscription_parameters", "semantico");
                });

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipient_subscription_recipients_recipients_id");

                    b.HasOne("Semantico.Core.Data.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipient_subscription_subscriptions_subscriptions_id");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiAlertConfiguration", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_alert_configurations_data_sources_data_source_id");

                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ai_alert_configurations_subscriptions_subscription_id");

                    b.Navigation("DataSource");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiConversationHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.AiAlertConfiguration", "AiAlertConfiguration")
                        .WithMany("ConversationHistory")
                        .HasForeignKey("AiAlertConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_conversation_histories_ai_alert_configurations_ai_alert_");

                    b.Navigation("AiAlertConfiguration");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiUsageMetrics", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .HasConstraintName("fk_ai_usage_metrics_data_sources_data_source_id");

                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .HasConstraintName("fk_ai_usage_metrics_queries_query_id");

                    b.Navigation("DataSource");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AnomalyBaseline", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_baselines_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AnomalyConfig", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_configs_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AnomalyEvent", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_anomaly_events_notifications_notification_id");

                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_events_subscriptions_subscription_id");

                    b.Navigation("Notification");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationJob", "MigrationJob")
                        .WithMany("Executions")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_migration_executions_migration_jobs_migration_job_id");

                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", "ParentExecution")
                        .WithMany()
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_migration_executions_migration_executions_parent_execution_");

                    b.Navigation("MigrationJob");

                    b.Navigation("ParentExecution");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_migration_jobs_data_sources_data_source_id");

                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DestinationDataSource")
                        .WithMany()
                        .HasForeignKey("DestinationDataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_migration_jobs_data_sources_destination_data_source_id");

                    b.Navigation("DataSource");

                    b.Navigation("DestinationDataSource");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataSourceDocumentation", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_source_documentations_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DocumentationAgentRun", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentation_agent_runs_data_sources_data_source_id");

                    b.HasOne("Semantico.Core.Data.Entities.DataSourceDocumentation", "Documentation")
                        .WithMany()
                        .HasForeignKey("DocumentationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documentation_agent_runs_data_source_documentations_documen");

                    b.Navigation("DataSource");

                    b.Navigation("Documentation");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DocumentationSection", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSourceDocumentation", "Documentation")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentation_sections_data_source_documentations_documenta");

                    b.Navigation("Documentation");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DocumentationVersion", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSourceDocumentation", "Documentation")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentation_versions_data_source_documentations_documenta");

                    b.Navigation("Documentation");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.ColumnMetadata", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", "DatabaseMetadata")
                        .WithMany("Columns")
                        .HasForeignKey("DatabaseMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_column_metadata_database_metadata_database_metadata_id");

                    b.Navigation("DatabaseMetadata");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_database_metadata_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.IndexMetadata", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", "DatabaseMetadata")
                        .WithMany("Indexes")
                        .HasForeignKey("DatabaseMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_index_metadata_database_metadata_database_metadata_id");

                    b.Navigation("DatabaseMetadata");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryExecutionHistory", "QueryExecutionHistory")
                        .WithMany("Notifications")
                        .HasForeignKey("QueryExecutionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_query_execution_history_query_execution_histo");

                    b.HasOne("Semantico.Core.Data.Entities.Recipient", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_recipients_recipient_id");

                    b.HasOne("Semantico.Core.Data.Entities.QueryTask", "Task")
                        .WithMany("Notifications")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notifications_query_tasks_task_id");

                    b.Navigation("QueryExecutionHistory");

                    b.Navigation("Recipient");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("QueryExecutionHistory")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_execution_history_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_parameters_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany("QuerySteps")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_steps_data_sources_data_source_id");

                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Steps")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_steps_queries_query_id");

                    b.Navigation("DataSource");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryStep", "QueryStep")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_step_parameters_query_steps_query_step_id");

                    b.Navigation("QueryStep");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryTask", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_query_tasks_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("Parameters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_parameters_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AiAlertConfiguration", b =>
                {
                    b.Navigation("ConversationHistory");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataSource", b =>
                {
                    b.Navigation("QuerySteps");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataSourceDocumentation", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Indexes");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryTask", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("QueryExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
