// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Semantico.Api.Data;

#nullable disable

namespace Semantico.Api.Migrations
{
    [DbContext(typeof(SemanticoContext))]
    partial class SemanticoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("semantico")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Semantico.Api.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", "semantico");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "moberg",
                            Value = "AQAAAAIAAYagAAAAECWEQ1jq8CPkruy8QrQy4eQqwKjFAQ2tt8wW/tH7zCype5L2asjL4W9+uBdvLMvPNQ=="
                        });
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_notifications_subscription_id");

                    b.ToTable("notifications", "semantico");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", "semantico");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("SqlValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_value");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_queries_project_id");

                    b.ToTable("queries", "semantico");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placeholder");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_query_parameters");

                    b.HasIndex("QueryId", "Placeholder")
                        .IsUnique()
                        .HasDatabaseName("ix_query_parameters_query_id_placeholder");

                    b.ToTable("query_parameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_subscriptions_query_id");

                    b.ToTable("subscriptions", "semantico");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.SubscriptionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("QueryPlaceholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_placeholder");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_subscription_parameters");

                    b.HasIndex("SubscriptionId", "QueryPlaceholder")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_parameters_subscription_id_query_placeholder");

                    b.ToTable("subscription_parameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Notification", b =>
                {
                    b.HasOne("Semantico.Api.Data.Entities.Subscription", "Subscription")
                        .WithMany("Notifications")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Query", b =>
                {
                    b.HasOne("Semantico.Api.Data.Entities.Project", "Project")
                        .WithMany("Queries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queries_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.QueryParameter", b =>
                {
                    b.HasOne("Semantico.Api.Data.Entities.Query", "Query")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_parameters_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Subscription", b =>
                {
                    b.HasOne("Semantico.Api.Data.Entities.Query", "Query")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.SubscriptionParameter", b =>
                {
                    b.HasOne("Semantico.Api.Data.Entities.Subscription", "Subscription")
                        .WithMany("Parameters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_parameters_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("Queries");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Query", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Semantico.Api.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
