using Beacon.Core.Data.Entities.Base;
using Beacon.Core.Data.Enums;

namespace Beacon.Core.Data.Entities;

/// <summary>
/// An AI Actor that autonomously monitors a data source by creating queries,
/// subscriptions, analyzing results, and sending notifications.
/// </summary>
public class AiActor : ArchivableBaseEntity
{
    /// <summary>
    /// Display name for the actor
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// High-level instructions for what the actor should monitor
    /// (e.g., "monitor transactions for unusual activity")
    /// </summary>
    public string Instructions { get; set; } = null!;

    /// <summary>
    /// Additional context about the data source, business rules, or monitoring requirements
    /// </summary>
    public string? AdditionalContext { get; set; }

    /// <summary>
    /// The data source this actor monitors
    /// </summary>
    public int DataSourceId { get; set; }

    /// <summary>
    /// Current status of the actor
    /// </summary>
    public AiActorStatus Status { get; set; } = AiActorStatus.Draft;

    /// <summary>
    /// Maximum number of queries the actor can create
    /// </summary>
    public int MaxQueries { get; set; } = 10;

    /// <summary>
    /// Maximum number of subscriptions per query the actor can create
    /// </summary>
    public int MaxSubscriptionsPerQuery { get; set; } = 3;

    /// <summary>
    /// Whether plans generated by this actor require user approval before execution.
    /// When true, the actor generates plans that must be approved.
    /// When false, the actor can execute changes autonomously.
    /// </summary>
    public bool RequiresApproval { get; set; } = true;

    /// <summary>
    /// User who created this actor
    /// </summary>
    public string? CreatedByUserId { get; set; }

    /// <summary>
    /// Total tokens used across all think cycles
    /// </summary>
    public int TotalTokensUsed { get; set; }

    /// <summary>
    /// Total estimated cost across all think cycles
    /// </summary>
    public decimal TotalCost { get; set; }

    /// <summary>
    /// Last time the actor completed a think cycle
    /// </summary>
    public DateTime? LastThinkTime { get; set; }

    /// <summary>
    /// Total number of think cycles completed
    /// </summary>
    public int ThinkCount { get; set; }

    /// <summary>
    /// Error message if actor is in Failed status
    /// </summary>
    public string? LastError { get; set; }

    // Navigation properties
    public DataSource DataSource { get; set; } = null!;
    public List<AiActorExecution> Executions { get; set; } = new();
    public List<AiActorConversation> Conversations { get; set; } = new();
    public List<AiActorPlan> Plans { get; set; } = new();
    public List<Query> Queries { get; set; } = new();
    public List<Subscription> Subscriptions { get; set; } = new();
}
