// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Semantico.Core.PostgreSql.Data;

#nullable disable

namespace Semantico.Core.PostgreSql.Migrations
{
    [DbContext(typeof(PostgreSqlSemanticoContext))]
    partial class PostgreSqlSemanticoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("semantico")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.Property<int>("RecipientsId")
                        .HasColumnType("integer")
                        .HasColumnName("recipients_id");

                    b.Property<int>("SubscriptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("subscriptions_id");

                    b.HasKey("RecipientsId", "SubscriptionsId")
                        .HasName("pk_recipient_subscription");

                    b.HasIndex("SubscriptionsId")
                        .HasDatabaseName("ix_recipient_subscription_subscriptions_id");

                    b.ToTable("recipient_subscription", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DestinationRowsWritten")
                        .HasColumnType("integer")
                        .HasColumnName("destination_rows_written");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("EstimatedTotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_total_rows");

                    b.Property<string>("ExecutedQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("executed_query");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("integer")
                        .HasColumnName("migration_job_id");

                    b.Property<int?>("ParentExecutionId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_execution_id");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<string>("QueryParameters")
                        .HasColumnType("text")
                        .HasColumnName("query_parameters");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("retry_attempt");

                    b.Property<int>("RowsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("rows_failed");

                    b.Property<int>("RowsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("rows_skipped");

                    b.Property<int>("SourceRowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("source_rows_read");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TransformationApplied")
                        .HasColumnType("text")
                        .HasColumnName("transformation_applied");

                    b.HasKey("Id")
                        .HasName("pk_migration_executions");

                    b.HasIndex("MigrationJobId")
                        .HasDatabaseName("ix_migration_executions_migration_job_id");

                    b.HasIndex("ParentExecutionId")
                        .HasDatabaseName("ix_migration_executions_parent_execution_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_migration_executions_started_at");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_migration_executions_status_started_at");

                    b.ToTable("migration_executions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_on");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DestinationProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_project_id");

                    b.Property<string>("DestinationTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_table");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.Property<string>("Schedule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schedule");

                    b.Property<int>("TimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_minutes");

                    b.Property<string>("TransformationScript")
                        .HasColumnType("text")
                        .HasColumnName("transformation_script");

                    b.Property<bool>("ValidateBeforeExecution")
                        .HasColumnType("boolean")
                        .HasColumnName("validate_before_execution");

                    b.HasKey("Id")
                        .HasName("pk_migration_jobs");

                    b.HasIndex("DestinationProjectId")
                        .HasDatabaseName("ix_migration_jobs_destination_project_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_migration_jobs_project_id");

                    b.HasIndex("IsEnabled", "ArchivedTime")
                        .HasDatabaseName("ix_migration_jobs_is_enabled_archived_time");

                    b.ToTable("migration_jobs", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("QueryExecutionHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_execution_history_id");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Results")
                        .HasColumnType("text")
                        .HasColumnName("results");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("QueryExecutionHistoryId")
                        .HasDatabaseName("ix_notifications_query_execution_history_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notifications_recipient_id");

                    b.ToTable("notifications", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DatabaseEngineType")
                        .HasColumnType("integer")
                        .HasColumnName("database_engine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FinalQuery")
                        .HasColumnType("text")
                        .HasColumnName("final_query");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.ToTable("queries", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompiledSql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compiled_sql");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<double>("ExecutionTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("execution_time_ms");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("notification_status");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_query_execution_history");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_query_execution_history_subscription_id");

                    b.ToTable("query_execution_history", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placeholder");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_query_parameters");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_query_parameters_query_id");

                    b.ToTable("query_parameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<string>("SqlValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_value");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_query_steps");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_query_steps_project_id");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_query_steps_query_id");

                    b.ToTable("query_steps", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Placeholder")
                        .HasColumnType("text")
                        .HasColumnName("placeholder");

                    b.Property<int>("QueryStepId")
                        .HasColumnType("integer")
                        .HasColumnName("query_step_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_query_step_parameters");

                    b.HasIndex("QueryStepId")
                        .HasDatabaseName("ix_query_step_parameters_query_step_id");

                    b.ToTable("query_step_parameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<int?>("ResultAttachmentType")
                        .HasColumnType("integer")
                        .HasColumnName("result_attachment_type");

                    b.HasKey("Id")
                        .HasName("pk_recipients");

                    b.ToTable("recipients", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IncludeAttachment")
                        .HasColumnType("boolean")
                        .HasColumnName("include_attachment");

                    b.Property<int?>("MaxRows")
                        .HasColumnType("integer")
                        .HasColumnName("max_rows");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<bool>("ShowQuery")
                        .HasColumnType("boolean")
                        .HasColumnName("show_query");

                    b.Property<bool>("StoreResults")
                        .HasColumnType("boolean")
                        .HasColumnName("store_results");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_subscriptions_query_id");

                    b.ToTable("subscriptions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("QueryPlaceholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_placeholder");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_subscription_parameters");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_parameters_subscription_id");

                    b.ToTable("subscription_parameters", "semantico");
                });

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipient_subscription_recipients_recipients_id");

                    b.HasOne("Semantico.Core.Data.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipient_subscription_subscriptions_subscriptions_id");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationJob", "MigrationJob")
                        .WithMany("Executions")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_migration_executions_migration_jobs_migration_job_id");

                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", "ParentExecution")
                        .WithMany()
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_migration_executions_migration_executions_parent_execution_");

                    b.Navigation("MigrationJob");

                    b.Navigation("ParentExecution");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Project", "DestinationProject")
                        .WithMany()
                        .HasForeignKey("DestinationProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_migration_jobs_projects_destination_project_id");

                    b.HasOne("Semantico.Core.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_migration_jobs_projects_project_id");

                    b.Navigation("DestinationProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryExecutionHistory", "QueryExecutionHistory")
                        .WithMany("Notifications")
                        .HasForeignKey("QueryExecutionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_query_execution_history_query_execution_histo");

                    b.HasOne("Semantico.Core.Data.Entities.Recipient", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_recipients_recipient_id");

                    b.Navigation("QueryExecutionHistory");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("QueryExecutionHistory")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_execution_history_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_parameters_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Project", "Project")
                        .WithMany("QuerySteps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_steps_projects_project_id");

                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Steps")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_steps_queries_query_id");

                    b.Navigation("Project");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryStep", "QueryStep")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_step_parameters_query_steps_query_step_id");

                    b.Navigation("QueryStep");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("Parameters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_parameters_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Project", b =>
                {
                    b.Navigation("QuerySteps");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("QueryExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
