// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Semantico.Core.SqlServer.Data;

#nullable disable

namespace Semantico.Core.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerSemanticoContext))]
    partial class SqlServerSemanticoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("semantico")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.Property<int>("RecipientsId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionsId")
                        .HasColumnType("int");

                    b.HasKey("RecipientsId", "SubscriptionsId");

                    b.HasIndex("SubscriptionsId");

                    b.ToTable("RecipientSubscription", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationRowsWritten")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EstimatedTotalRows")
                        .HasColumnType("int");

                    b.Property<string>("ExecutedQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentExecutionId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("int");

                    b.Property<string>("QueryParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<int>("RowsFailed")
                        .HasColumnType("int");

                    b.Property<int>("RowsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("SourceRowsRead")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransformationApplied")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status", "StartedAt");

                    b.ToTable("MigrationExecutions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DestinationProjectId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TransformationScript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValidateBeforeExecution")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DestinationProjectId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("IsEnabled", "ArchivedTime");

                    b.ToTable("MigrationJobs", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QueryExecutionHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryExecutionHistoryId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Notifications", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DatabaseEngineType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalQuery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Queries", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompiledSql")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExecutionTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("QueryExecutionHistory", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryParameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<string>("SqlValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QueryId");

                    b.ToTable("QuerySteps", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueryStepId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryStepId");

                    b.ToTable("QueryStepParameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<int?>("ResultAttachmentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipients", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeAttachment")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxRows")
                        .HasColumnType("int");

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowQuery")
                        .HasColumnType("bit");

                    b.Property<bool>("StoreResults")
                        .HasColumnType("bit");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("Subscriptions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueryPlaceholder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionParameters", "semantico");
                });

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationJob", "MigrationJob")
                        .WithMany("Executions")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", "ParentExecution")
                        .WithMany()
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MigrationJob");

                    b.Navigation("ParentExecution");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Project", "DestinationProject")
                        .WithMany()
                        .HasForeignKey("DestinationProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryExecutionHistory", "QueryExecutionHistory")
                        .WithMany("Notifications")
                        .HasForeignKey("QueryExecutionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.Recipient", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryExecutionHistory");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("QueryExecutionHistory")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Project", "Project")
                        .WithMany("QuerySteps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Steps")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryStep", "QueryStep")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryStep");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("Parameters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Project", b =>
                {
                    b.Navigation("QuerySteps");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("QueryExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
