// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Semantico.Core.SqlServer.Data;

#nullable disable

namespace Semantico.Core.SqlServer.Data.Migrations
{
    [DbContext(typeof(SqlServerSemanticoContext))]
    partial class SqlServerSemanticoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("semantico")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.Property<int>("RecipientsId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionsId")
                        .HasColumnType("int");

                    b.HasKey("RecipientsId", "SubscriptionsId");

                    b.HasIndex("SubscriptionsId");

                    b.ToTable("RecipientSubscription", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AlertingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastNotificationAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LatestResultCount")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime")
                        .HasDatabaseName("IX_Task_CreatedTime");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Task_SubscriptionId_Unique");

                    b.HasIndex("Resolved", "CreatedTime")
                        .HasDatabaseName("IX_Task_Resolved_CreatedTime");

                    b.ToTable("Tasks", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationRowsWritten")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EstimatedTotalRows")
                        .HasColumnType("int");

                    b.Property<string>("ExecutedQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentExecutionId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("int");

                    b.Property<string>("QueryParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<int>("RowsFailed")
                        .HasColumnType("int");

                    b.Property<int>("RowsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("SourceRowsRead")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransformationApplied")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status", "StartedAt");

                    b.ToTable("MigrationExecutions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DestinationDataSourceId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TransformationScript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValidateBeforeExecution")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("DestinationDataSourceId");

                    b.HasIndex("IsEnabled", "ArchivedTime");

                    b.ToTable("MigrationJobs", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DatabaseEngineType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataSources", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.ColumnMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DatabaseMetadataId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ForeignKeyColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ForeignKeyTable")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsForeignKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseMetadataId");

                    b.HasIndex("DatabaseMetadataId", "ColumnName");

                    b.ToTable("ColumnMetadata", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastRefreshed")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("LastRefreshed");

                    b.HasIndex("DataSourceId", "SchemaName", "TableName")
                        .IsUnique();

                    b.ToTable("DatabaseMetadata", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.IndexMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Columns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DatabaseMetadataId")
                        .HasColumnType("int");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseMetadataId");

                    b.ToTable("IndexMetadata", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QueryExecutionHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryExecutionHistoryId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("TaskId");

                    b.ToTable("Notifications", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalQuery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Queries", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompiledSql")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExecutionTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("QueryExecutionHistory", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryParameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<string>("SqlValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("QueryId");

                    b.ToTable("QuerySteps", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueryStepId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryStepId");

                    b.ToTable("QueryStepParameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipients", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CreateTasks")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeAttachment")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxRows")
                        .HasColumnType("int");

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<int?>("ResultAttachmentType")
                        .HasColumnType("int");

                    b.Property<bool>("ShowQuery")
                        .HasColumnType("bit");

                    b.Property<bool>("StoreResults")
                        .HasColumnType("bit");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("Subscriptions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueryPlaceholder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionParameters", "semantico");
                });

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AlertingTask", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationJob", "MigrationJob")
                        .WithMany("Executions")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.DataMigration.MigrationExecutionHistory", "ParentExecution")
                        .WithMany()
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MigrationJob");

                    b.Navigation("ParentExecution");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DestinationDataSource")
                        .WithMany()
                        .HasForeignKey("DestinationDataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("DestinationDataSource");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.ColumnMetadata", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", "DatabaseMetadata")
                        .WithMany("Columns")
                        .HasForeignKey("DatabaseMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseMetadata");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.IndexMetadata", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", "DatabaseMetadata")
                        .WithMany("Indexes")
                        .HasForeignKey("DatabaseMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseMetadata");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Notification", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryExecutionHistory", "QueryExecutionHistory")
                        .WithMany("Notifications")
                        .HasForeignKey("QueryExecutionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.Recipient", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.AlertingTask", "Task")
                        .WithMany("Notifications")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("QueryExecutionHistory");

                    b.Navigation("Recipient");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("QueryExecutionHistory")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.DataSource", "DataSource")
                        .WithMany("QuerySteps")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Steps")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStepParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.QueryStep", "QueryStep")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryStep");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("Parameters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.AlertingTask", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataMigration.MigrationJob", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.DataSource", b =>
                {
                    b.Navigation("QuerySteps");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Metadata.DatabaseMetadata", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Indexes");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryStep", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("QueryExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
