// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Semantico.Core.Data;

#nullable disable

namespace Semantico.Core.Data.Migrations
{
    [DbContext(typeof(SemanticoContext))]
    [Migration("20250410000000_UpdateNotificationSentToStatus")]
    partial class UpdateNotificationSentToStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Migration snapshot code would be here
            // For brevity, we're not including the full model snapshot as it would be generated
        }
    }
}