// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Semantico.Core.Data;

#nullable disable

namespace Semantico.Core.Data.Migrations
{
    [DbContext(typeof(SemanticoContext))]
    partial class SemanticoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("semantico")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.Property<int>("RecipientsId")
                        .HasColumnType("integer")
                        .HasColumnName("recipients_id");

                    b.Property<int>("SubscriptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("subscriptions_id");

                    b.HasKey("RecipientsId", "SubscriptionsId")
                        .HasName("pk_recipient_subscription");

                    b.HasIndex("SubscriptionsId")
                        .HasDatabaseName("ix_recipient_subscription_subscriptions_id");

                    b.ToTable("recipient_subscription", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DatabaseEngineType")
                        .HasColumnType("integer")
                        .HasColumnName("database_engine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("SqlValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_value");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_queries_project_id");

                    b.ToTable("queries", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompiledSql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compiled_sql");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_sent");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_query_execution_history");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_query_execution_history_subscription_id");

                    b.ToTable("query_execution_history", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placeholder");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_query_parameters");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_query_parameters_query_id");

                    b.ToTable("query_parameters", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<int?>("ResultAttachmentType")
                        .HasColumnType("integer")
                        .HasColumnName("result_attachment_type");

                    b.HasKey("Id")
                        .HasName("pk_recipients");

                    b.ToTable("recipients", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<int>("QueryId")
                        .HasColumnType("integer")
                        .HasColumnName("query_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_subscriptions_query_id");

                    b.ToTable("subscriptions", "semantico");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("QueryPlaceholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_placeholder");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_subscription_parameters");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_parameters_subscription_id");

                    b.ToTable("subscription_parameters", "semantico");
                });

            modelBuilder.Entity("RecipientSubscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipient_subscription_recipients_recipients_id");

                    b.HasOne("Semantico.Core.Data.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipient_subscription_subscriptions_subscriptions_id");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Project", "Project")
                        .WithMany("Queries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queries_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryExecutionHistory", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("QueryExecutionHistory")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_execution_history_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.QueryParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_parameters_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Query", "Query")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.SubscriptionParameter", b =>
                {
                    b.HasOne("Semantico.Core.Data.Entities.Subscription", "Subscription")
                        .WithMany("Parameters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_parameters_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Project", b =>
                {
                    b.Navigation("Queries");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Query", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Semantico.Core.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("QueryExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
