using Beacon.AI.Services.Knowledge;
using Beacon.Core.Data;
using Beacon.Core.Data.Entities;
using Beacon.Core.Data.Entities.Metadata;
using Beacon.Core.Data.Entities.Projects;
using Beacon.Core.Data.Enums;
using Beacon.Core.HostData;
using Beacon.Core.HostDocs;
using Beacon.MCP.Services;
using Beacon.MCP.Tools;
using Beacon.Tests.Common;
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using ModelContextProtocol.Protocol;
using Moq;
using NUnit.Framework;

namespace Beacon.Tests.Unit.HostDocs;

/// <summary>
/// The <c>get_context format=agents_md</c> project brief: a deterministic markdown rendering (snapshot-style), the
/// data loader's ordering and caps, and the tool's format validation and audit on every path.
/// </summary>
[TestFixture]
public class ProjectBriefTests
{
    private const int ProjectId = 5;

    [Test]
    public void Render_ProducesTheExpectedBrief()
    {
        var data = new ProjectBriefData(
            "Netgiro",
            "Consumer financing platform.",
            [new BriefDataSource("NetgiroContext", DataSourceType.Database, DatabaseEngineType.MSSQL, true, true, 2)],
            [
                new BriefTable("NetgiroContext", "dbo", "Loans", "A loan | one per purchase", 12),
                new BriefTable("NetgiroContext", "dbo", "Customers", null, 8)
            ],
            40,
            [new BriefMaskedColumn("dbo", "Customers", "Email")],
            [new BriefGlossaryTerm("Active loan", "A loan with an unpaid\ninstallment.")],
            31,
            [new ImportedDocumentSummary(1, "docs:dir:docs/wiki", "README.md", "Netgiro Platform", DateTime.UnixEpoch)],
            1);

        var brief = ProjectBriefService.Render(data);

        brief.Should().Be("""
            # Netgiro — Beacon project brief

            > Generated by Beacon `get_context` (format `agents_md`) from the project's catalog. Regenerate it when the project changes.

            Consumer financing platform.

            ## Working with this project through Beacon

            Beacon exposes this project over MCP. Access is **read-only**: only SELECT / WITH statements run, and write statements are rejected at several layers — do not attempt them.

            For hand-written SQL use `get_query_context` → `dry_run` → `query`:

            1. `search` — find tables, columns and documents by keyword.
            2. `get_query_context` — grounding for one question: schemas with sample values, verified join paths, example queries, glossary.
            3. `dry_run` — validate the SQL through every safety gate without executing it.
            4. `query` — run the validated SQL; results are row-capped and masked columns come back masked.

            Also available: `get_context` (project overview), `get_documentation` (documentation, table detail, and the documents below via `document: "<path>"`), `ask` (natural-language question, when AI is enabled on the Beacon host) and `feedback` (report whether an `ask` answer was correct).

            Rules:

            - Masked columns stay masked: never try to unmask, reconstruct or infer their values.
            - Excluded tables and columns are not visible to Beacon; if something is missing, it is out of scope, not hidden.
            - Pass `project_id` on every call when your credentials reach more than one project.

            ## Data sources

            | Data source | Engine | Tables | Access |
            | --- | --- | --- | --- |
            | NetgiroContext | MSSQL | 2 | host-managed, read-only (an allow-listed slice of the host application's model) |

            ## Key tables

            The 2 best-described of 40 tables; use `search` for the rest.

            | Table | Data source | Columns | Description |
            | --- | --- | --- | --- |
            | `dbo.Loans` | NetgiroContext | 12 | A loan \| one per purchase |
            | `dbo.Customers` | NetgiroContext | 8 |  |

            ## Masked columns

            Values of these columns are masked in every query result:

            - `dbo.Customers.Email`

            ## Glossary

            - **Active loan** — A loan with an unpaid installment.
            - … 30 more; `get_query_context` returns the relevant terms per question.

            ## Documents

            Fetch one with `get_documentation` and `document: "<path>"`; `search` also matches their text.

            - Netgiro Platform — `README.md`

            """);
    }

    [Test]
    public void Render_EmptyProject_OmitsOptionalSections()
    {
        var data = new ProjectBriefData("Empty", null, [], [], 0, [], [], 0, [], 0);

        var brief = ProjectBriefService.Render(data);

        brief.Should().Contain("No data sources are linked to this project.");
        brief.Should().NotContain("## Key tables");
        brief.Should().NotContain("## Glossary");
        brief.Should().NotContain("## Documents");
        brief.Should().Contain("`get_documentation` (documentation, table detail)");
    }

    [Test]
    public async Task BuildAgentsMd_OrdersTablesByDescriptionThenRelations_AndScopesToTheProject()
    {
        var store = new DocsStore();
        var dataSource = new DataSource
        {
            Id = 1,
            Name = "NetgiroContext",
            DataSourceType = DataSourceType.Database,
            DatabaseEngineType = DatabaseEngineType.MSSQL,
            EncryptedConnectionData = "enc",
            IsReadOnly = true,
            HostManagedKey = "efcore:NetgiroContext"
        };
        store.Projects.Add(new Project { Id = ProjectId, Name = "Netgiro", Description = "Financing." });
        store.ListFor<ProjectDataSource>().Add(new ProjectDataSource { ProjectId = ProjectId, DataSourceId = 1, DataSource = dataSource });

        var plain = Table(10, dataSource, "Audit", null);
        var related = Table(11, dataSource, "Claims", null);
        related.Columns.Add(Column(related, "LoanId", null, isForeignKey: true));
        var described = Table(12, dataSource, "Loans", "Loans.");
        var customers = Table(13, dataSource, "Customers", null);
        customers.Columns.Add(Column(customers, "Email", "Mail " + HostModelReader.MaskedDescriptionMarker));
        store.ListFor<DatabaseMetadata>().AddRange([plain, related, described, customers]);
        store.ListFor<ColumnMetadata>().AddRange(store.ListFor<DatabaseMetadata>().SelectMany(x => x.Columns));

        store.ListFor<McpGlossaryTerm>().Add(new McpGlossaryTerm { Id = 1, ProjectId = ProjectId, Term = "Loan", Definition = "Money lent." });
        store.ListFor<McpGlossaryTerm>().Add(new McpGlossaryTerm { Id = 2, ProjectId = ProjectId, Term = "Inactive", Definition = "x", IsActive = false });
        store.ListFor<McpGlossaryTerm>().Add(new McpGlossaryTerm { Id = 3, ProjectId = 99, Term = "Foreign", Definition = "Other project." });
        store.Documents.Add(new ProjectImportedDocument { Id = 1, ProjectId = ProjectId, SourceKey = "k", Path = "README.md", Title = "Readme", ContentHash = "h", Content = "c" });
        store.Documents.Add(new ProjectImportedDocument { Id = 2, ProjectId = 99, SourceKey = "k", Path = "other.md", Title = "Other", ContentHash = "h", Content = "c" });

        var service = new ProjectBriefService(store.Factory().Object);

        var brief = await service.BuildAgentsMdAsync(ProjectId, CancellationToken.None);
        var again = await service.BuildAgentsMdAsync(ProjectId, CancellationToken.None);

        brief.Should().Be(again, "the brief is deterministic");
        brief!.IndexOf("`dbo.Loans`", StringComparison.Ordinal).Should().BeLessThan(brief.IndexOf("`dbo.Customers`", StringComparison.Ordinal));
        brief.IndexOf("`dbo.Customers`", StringComparison.Ordinal).Should().BeLessThan(brief.IndexOf("`dbo.Claims`", StringComparison.Ordinal));
        brief.IndexOf("`dbo.Claims`", StringComparison.Ordinal).Should().BeLessThan(brief.IndexOf("`dbo.Audit`", StringComparison.Ordinal));
        brief.Should().Contain("| NetgiroContext | MSSQL | 4 | host-managed, read-only");
        brief.Should().Contain("- `dbo.Customers.Email`");
        brief.Should().Contain("- **Loan** — Money lent.");
        brief.Should().NotContain("Inactive").And.NotContain("Foreign").And.NotContain("other.md");
        brief.Should().Contain("- Readme — `README.md`");
    }

    [Test]
    public async Task BuildAgentsMd_UnknownProject_ReturnsNull()
    {
        var service = new ProjectBriefService(new DocsStore().Factory().Object);

        (await service.BuildAgentsMdAsync(404, CancellationToken.None)).Should().BeNull();
    }

    [Test]
    public async Task GetContext_AgentsMd_ReturnsTheBrief_AndAudits()
    {
        var (tool, briefService, auditFactory) = BuildTool();
        briefService
            .Setup(x => x.BuildAgentsMdAsync(ProjectId, It.IsAny<CancellationToken>()))
            .ReturnsAsync("# Brief\n");

        var result = await tool.ExecuteAsync(format: "AGENTS_MD", cancellationToken: CancellationToken.None);

        result.IsError.Should().NotBe(true);
        Text(result).Should().Be("# Brief\n");
        auditFactory.Verify(x => x.CreateDbContextAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Test]
    public async Task GetContext_AgentsMd_Failure_IsAuditedAndCallerSafe()
    {
        var (tool, briefService, auditFactory) = BuildTool();
        briefService
            .Setup(x => x.BuildAgentsMdAsync(ProjectId, It.IsAny<CancellationToken>()))
            .ThrowsAsync(new InvalidOperationException("boom"));

        var result = await tool.ExecuteAsync(format: "agents_md", cancellationToken: CancellationToken.None);

        result.IsError.Should().BeTrue();
        auditFactory.Verify(x => x.CreateDbContextAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Test]
    public async Task GetContext_UnknownFormat_IsRejected_AndAudited_WithoutBuildingABrief()
    {
        var (tool, briefService, auditFactory) = BuildTool();

        var result = await tool.ExecuteAsync(format: "yaml", cancellationToken: CancellationToken.None);

        result.IsError.Should().BeTrue();
        Text(result).Should().Be("format must be 'overview' or 'agents_md'.");
        briefService.Verify(x => x.BuildAgentsMdAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()), Times.Never);
        auditFactory.Verify(x => x.CreateDbContextAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    private static (GetContextTool Tool, Mock<IProjectBriefService> Brief, Mock<IDbContextFactory<BeaconContext>> AuditFactory) BuildTool()
    {
        var auditFactory = new Mock<IDbContextFactory<BeaconContext>>();
        var auditService = new McpAuditService(auditFactory.Object, SettingsProviderMock.Create().Object, new HttpContextAccessor(), NullLogger<McpAuditService>.Instance);
        var briefService = new Mock<IProjectBriefService>();
        var tool = new GetContextTool(
            new Mock<IKnowledgeGraphService>().Object,
            new Mock<IDbContextFactory<BeaconContext>>().Object,
            briefService.Object,
            new McpProjectContext { UserId = 1, ApiKeyId = 9, AllowedProjectIds = [ProjectId] },
            auditService,
            NullLogger<GetContextTool>.Instance);

        return (tool, briefService, auditFactory);
    }

    private static DatabaseMetadata Table(int id, DataSource dataSource, string name, string? description) =>
        new()
        {
            Id = id,
            DataSourceId = dataSource.Id,
            DataSource = dataSource,
            SchemaName = "dbo",
            TableName = name,
            TableDescription = description
        };

    private static ColumnMetadata Column(DatabaseMetadata table, string name, string? description, bool isForeignKey = false) =>
        new()
        {
            DatabaseMetadataId = table.Id,
            DatabaseMetadata = table,
            ColumnName = name,
            DataType = "int",
            Description = description,
            IsForeignKey = isForeignKey
        };

    private static string Text(CallToolResult result) => result.Content.OfType<TextContentBlock>().Single().Text;
}
