name: Build

on:
  push:
    branches: [ task#5/add-github-build-script ]

jobs:
  build:
    name: "Build Semantico"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: "Build application"
      run: |
        cd Semantico.Api
        dotnet build --configuration Release

    - name: "Publish application"
      run: |
        cd Semantico.Api
        dotnet publish -c Release -o ./publish

    - name: "Upload artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: "build-artifacts"
        path: |
          ./publish/**
