name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
        
jobs:
    build-images:
        name: "Build Images"
        runs-on: ubuntu-latest
        env:
          IMAGE_TAG: ${{ github.sha }}
        steps:
          - name: Download a services artifacts
            uses: actions/download-artifact@v3
            with:
              name: build-artifacts
    
          - name: "Unzip artifacts"
            run: unzip services.zip

          - name: "Configure AWS credentials"
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.aws-access-key-id }}
              aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
              aws-region: ${{ secrets.aws_region }}
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
          
          - name: "Build images"
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            run: |
              docker build -f Dockerfile --target semantico-api -t $ECR_REGISTRY/semantico:$IMAGE_TAG -t $ECR_REGISTRY/semantico-api:latest .
          - name: "Push images" 
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            run: |
              # Push semantico images to registry
              docker push $ECR_REGISTRY/semantico-api:$IMAGE_TAG
              docker push $ECR_REGISTRY/semantico-api:latest

    deploy-services:
      name: Deploy services
      needs: build-images
      runs-on: ubuntu-latest
      env: 
        cluster: ${{ vars.AWS_CLUSTER }}
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.aws-access-key-id }}
            aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
            aws-region: ${{ env.aws_region }}
            
        - name: Deploy Semantico
          run: aws ecs update-service --cluster $cluster --force-new-deployment --service semantico-api
