name: Build

on:
  workflow_call:

jobs:
  build:
    name: "Build Semantico"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
        
    - name: Install dependencies
      run: |
        cd Semantico.Api
        dotnet restore

    - name: "Build application"
      run: dotnet build --configuration Release --no-restore

    - name: "Publish application"
      run: dotnet publish --no-build -c Release -p:PublishDir=./publish

    - name: "Create service.zip"
      working-directory: Semantico.Api
      run: zip -r services.zip Dockerfile publish

    - name: "Upload artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: "build-artifacts"
        path: ./Semantico.Api/services.zip
        if-no-files-found: error